language: ruby

rvm:
  - 2.0.0

services:
  - mysql

script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

before_script:
  - mysql -e 'create database coleta-seletiva_test;'

env:
  - RAILS_ENV=test